environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm -g install npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

cache:
  - node_modules
  - '%APPDATA%\npm-cache'

build_script:
  - npm run compile

test_script:
  - npm run lint
  - npm test
