language: node_js

node_js:
  - 9
  - 8
  - 7
  - 6

script:
  - npm run compile
  - npm run lint
  - npm test -- --coverage --mapCoverage

after_success:
  - npm run coveralls < coverage/lcov.info

cache:
  directories:
    - node_modules
